changelog:
  categories:
    - title: Features
      labels: ["type: feat"]
    - title: Bug Fixes
      labels: ["type: fix"]
    - title: Performance
      labels: ["type: perf"]
    - title: Documentation
      labels: ["type: docs"]
    - title: Maintenance
      labels: ["type: chore", "type: build", "type: ci", "type: refactor", "type: style", "type: test", "type: revert"]
    - title: Other Changes
      labels: ["*"]
