export const LEGACY_CANVAS_UI_TOOL_NAME = "canvas_ui";
export const CANVAS_UI_CLIENT_TOOL_NAME = "canvas_ui_control";

/**
 * Action discriminator generated by the SDK for the client-defined Canvas UI
 * tool (`ClientAction_<tool-name>`). Keep the SDK naming convention contained
 * here instead of repeating its generated class name throughout the frontend.
 */
export const CANVAS_UI_CLIENT_ACTION_KIND =
  `ClientAction_${CANVAS_UI_CLIENT_TOOL_NAME}` as const;
